name: genx_bill
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.0
  google_fonts: ^6.1.0
  fl_chart: ^0.66.0
  intl: ^0.20.2
  pdf: ^3.10.0
  printing: ^5.11.0
  uuid: ^4.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  animate_do: ^3.3.2
  flutter_animate: ^4.5.0
  glassmorphism: ^3.0.0
  path_provider: ^2.1.1
  mailer: ^6.1.0

  cupertino_icons: ^1.0.2
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  msix: ^3.16.7

flutter:
  generate: true
  uses-material-design: true
  
  assets:
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.jpg"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.jpg"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/icons/app_icon.jpg"
  linux:
    generate: true
    image_path: "assets/icons/app_icon.jpg"

msix_config:
  display_name: GenXBill
  publisher_display_name: GenXis Inc
  publisher: CN=GenXisInc, O=GenXisInc, L=Nagpur, S=Maharashtra, C=IN
  identity_name: com.genxis.genxbill
  msix_version: 1.0.0.0
  logo_path: assets/icons/app_icon.jpg
  capabilities: internetClient, location
